version: '2'
services:
  medikal-app:
    image: medikal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://medikal-mysql:3306/medikal?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://medikal-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://medikal-elasticsearch:9200
    ports:
      - 8080:8080
  medikal-mysql:
    extends:
      file: mysql.yml
      service: medikal-mysql
  medikal-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: medikal-elasticsearch
